/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author barbara
 */
public class CadastroItens extends javax.swing.JFrame {

    List<Item> itens = new ArrayList<>(); //crio uma lista para adicionar os itens

    public CadastroItens() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lNomeItem = new javax.swing.JLabel();
        tNomeItem = new javax.swing.JTextField();
        lValorUni = new javax.swing.JLabel();
        tValorUni = new javax.swing.JTextField();
        bCadastrar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CADASTRAR ITEM");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DADOS"));

        lNomeItem.setText("Nome do Item:");

        tNomeItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tNomeItemKeyPressed(evt);
            }
        });

        lValorUni.setText("Valor Unitário:");

        tValorUni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tValorUni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tValorUniKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lNomeItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tNomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lValorUni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNomeItem)
                    .addComponent(tNomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lValorUni)
                    .addComponent(tValorUni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        bCadastrar.setText("CADASTRAR");
        bCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bCadastrarKeyPressed(evt);
            }
        });

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 166, Short.MAX_VALUE)
                        .addComponent(bCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCadastrar)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        gravarItens(itens); //quando cancelar a operação eu gravo todos os itens que foi adicionado a lista e depois fecho a tela
        this.dispose();
    }//GEN-LAST:event_bCancelarActionPerformed

    private void tNomeItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNomeItemKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
            tValorUni.requestFocus(); //verifico se a tecla acionada é o enter, se for eu passo o focu para o valor unitário
    }//GEN-LAST:event_tNomeItemKeyPressed

    private void tValorUniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tValorUniKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) 
            bCadastrar.requestFocus(); //verifico se a tecla acionada é o enter, se for eu passo o focu para o botão de cadastrar
    }//GEN-LAST:event_tValorUniKeyPressed

    private void bCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bCadastrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //verifico se a tecla acionada é o enter, se for eu cadastro o item
            String nome = tNomeItem.getText(); //adiciono o nome digitado em uma string nome
            double valor = Double.parseDouble(tValorUni.getText()); //transformo o valor em uma variável do tipo double
            Item item = new Item(nome, valor); //crio um nome item com as informações acima

            if (itens.contains(item)) { //verifico se esse item já foi cadastro, se já eu informo na tela e seto as informações dos textos como vazia para nova digitação
                JOptionPane.showMessageDialog(null, "Informações já Cadastradas!");
                tNomeItem.setText("");
                tValorUni.setText("");
                tNomeItem.requestFocus();
            } else { //senão for igual, eu adiciono o item a lista de itens e seto as informações dos textos coom vazia para nova digitação
                itens.add(item);
                tNomeItem.setText("");
                tValorUni.setText("");
                tNomeItem.requestFocus();
            }
        }
    }//GEN-LAST:event_bCadastrarKeyPressed

    public void gravarItens(List<Item> itens) {
        File file = new File("itens.csv");  //crio um novo arquivo
        boolean exite = false;
        if (file.exists()) { //verifico se o arquivo já existe, caso sim eu seto a informação como verdadeira
            exite = true;
        }
        try {
            BufferedWriter arq = new BufferedWriter(new FileWriter(file, exite)); //atribuo o documento criado a um arquivo
            if (!exite) {
                arq.write("NOME ITEM;VALOR UNITARIO\n"); //se ele não exitir eu seto a primeira linha com as informações de nome do item e valor unitário
            }
            for (int i = 0; i < itens.size(); i++) {
                arq.write(itens.get(i).getNomeItem() + ";"); //gravo na primeira coluna o nome do item
                arq.write(itens.get(i).getValorUni() + ";"); //gravo na segunda coluna o valor do item
                arq.write("\n");  //pulo para a próxima linha
            }
            JOptionPane.showMessageDialog(null, "Informações Gravadas com Sucesso!");
            arq.close();
        } catch (IOException e) {
            Logger.getLogger(Item.class.getName()).log(Level.SEVERE, null, e);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCadastrar;
    private javax.swing.JButton bCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNomeItem;
    private javax.swing.JLabel lValorUni;
    private javax.swing.JTextField tNomeItem;
    private javax.swing.JTextField tValorUni;
    // End of variables declaration//GEN-END:variables
}
