/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author barbara
 */
public class FecharMesa extends javax.swing.JFrame {

    JLabel tValorTotal;
    List<Mesa> mesas = new ArrayList<>();
    JButton bAbrirMesa;

    public FecharMesa(JLabel tValorTotal, JButton bAbrirMesa) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        bPagar.setEnabled(false);           //este botão só ficará ativado após o valor do troco ser maior ou igual a zero
        this.bAbrirMesa = bAbrirMesa;       //passo por parametro o botão de abrir mesa, pois como meu programa apresenta algumas falhas, após fechar uma mesa tem que clicar nele novamente.
        tValorFatura.setText(tValorTotal.getText()); //passo por parametro o valor do consumo para setar no valor total da fatura
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bcFormaPag = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tNumMesa = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        rbDinheiro = new javax.swing.JRadioButton();
        rbCCredito = new javax.swing.JRadioButton();
        rbCDebito = new javax.swing.JRadioButton();
        rbVale = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        lTotalFatura = new javax.swing.JLabel();
        lValorPago = new javax.swing.JLabel();
        tValorPago = new javax.swing.JTextField();
        lTroco = new javax.swing.JLabel();
        tValorFatura = new javax.swing.JLabel();
        tTroco = new javax.swing.JLabel();
        bPagar = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FECHAR MESA");
        setResizable(false);

        tNumMesa.setEditable(false);
        tNumMesa.setText("MESA");
        tNumMesa.setToolTipText("");
        tNumMesa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tNumMesa.setOpaque(false);
        jScrollPane1.setViewportView(tNumMesa);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("FORMA DE PAGAMENTO"));

        bcFormaPag.add(rbDinheiro);
        rbDinheiro.setSelected(true);
        rbDinheiro.setText("DINHEIRO");

        bcFormaPag.add(rbCCredito);
        rbCCredito.setText("CARTÃO DE CRÉDITO");

        bcFormaPag.add(rbCDebito);
        rbCDebito.setText("CARTÃO DE DÉBITO");

        bcFormaPag.add(rbVale);
        rbVale.setText("VALE ALIMENTAÇÃO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbVale)
                    .addComponent(rbCDebito)
                    .addComponent(rbCCredito)
                    .addComponent(rbDinheiro))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbDinheiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCCredito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCDebito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVale))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("PAGAMENTO"));

        lTotalFatura.setText("TOTAL FATURA:");

        lValorPago.setText("VALOR PAGO:");

        tValorPago.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        tValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tValorPagoKeyReleased(evt);
            }
        });

        lTroco.setText("TROCO:");

        tValorFatura.setText("R$ 0,00");

        tTroco.setText("R$ 0,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lTotalFatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tValorFatura))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lValorPago)
                            .addComponent(lTroco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tTroco)
                            .addComponent(tValorPago))))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tValorFatura, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lTotalFatura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tValorPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lValorPago, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tTroco))
                .addGap(3, 3, 3))
        );

        bPagar.setText("PAGAR");
        bPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPagarActionPerformed(evt);
            }
        });

        bCancelar.setText("CANCELAR");
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bCancelar))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPagar)
                    .addComponent(bCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        this.dispose(); //quando clicar na opção cancelar, fecho a página
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPagarActionPerformed
        String pagamento = ""; //eu verifico qual botão foi selecionado sobre a forma de pagamento, colocando o valor em uma string.
        if (rbDinheiro.isSelected()) {
            pagamento = "Dinheiro";
        } else if (rbCCredito.isSelected()) {
            pagamento = "Cartão de Crédito";
        } else if (rbCDebito.isSelected()) {
            pagamento = "Cartão de Debito";
        } else if (rbVale.isSelected()) {
            pagamento = "Vale Alimentação";
        }
        Mesa mesa = new Mesa(tNumMesa.getText(), pagamento, Double.parseDouble(tValorFatura.getText())); //após eu faço um novo objeto mesa e seto todas as informações.
        mesas.add(mesa);  //depois coloco em uma lista de mesas e gravo no pdf
        gravarMesas(mesas);
        JOptionPane.showMessageDialog(null, "Pagamento Efetuado com Sucesso!");
        bAbrirMesa.setEnabled(true); //seto  o botão de Abrir mesa para poder ser clicado novamente.
        this.dispose();
    }//GEN-LAST:event_bPagarActionPerformed

    private void tValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tValorPagoKeyReleased
        double valorPago = Double.parseDouble(tValorPago.getText()); //crio uma variável para ver qual valor vai ser pago
        double valorTroco = valorPago - Double.parseDouble(tValorFatura.getText()); //crio uma variável de troco e atribuo o valor pago menos o valor total da fatura
        tTroco.setText(String.valueOf(valorTroco)); //seto o valor do troco no espaço de troco

        if (valorTroco < 0) { //eu verifico qual é o valor do troco
            bPagar.setEnabled(false);
        } else {
            bPagar.setEnabled(true); //só deixo o botão de Pagar ativado se o troco for maior ou igual a 0
        }
    }//GEN-LAST:event_tValorPagoKeyReleased

    public void gravarMesas(List<Mesa> mesas) {
        File file = new File("Faturamento_Dia.pdf");

        Document doc = new Document(); //crio um novo documento
        doc.setPageSize(PageSize.A4); //seto o tamanho da página, neste caso uma página A4

        try {
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(file)); //atribuo o documento criado a um arquivo

            doc.open(); //abro o documento

            doc.add(new Paragraph("MESA;PAGAMENTO;VALOR TOTAL\n")); //adiciono na primeira linha as informações que terá as demais linhas
            for (int i = 0; i < mesas.size(); i++) {
                doc.add(new Paragraph(mesas.get(i).getMesa() + ";" + mesas.get(i).getFormPagamento() + ";" + mesas.get(i).getValorPago() + "\n"));
            } //adiciono todas as informações na mesma linha e pulo uma linha para receber as próximas informações

            doc.close(); //fecho o documento
            writer.close(); //fecho o arquivo
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bPagar;
    private javax.swing.ButtonGroup bcFormaPag;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTotalFatura;
    private javax.swing.JLabel lTroco;
    private javax.swing.JLabel lValorPago;
    private javax.swing.JRadioButton rbCCredito;
    private javax.swing.JRadioButton rbCDebito;
    private javax.swing.JRadioButton rbDinheiro;
    private javax.swing.JRadioButton rbVale;
    private javax.swing.JTextPane tNumMesa;
    private javax.swing.JLabel tTroco;
    private javax.swing.JLabel tValorFatura;
    private javax.swing.JTextField tValorPago;
    // End of variables declaration//GEN-END:variables
}
