/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author barbara
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<JButton> bMesa; //crio um arraylist de botões para adicionar os botões da mesa

    public TelaPrincipal() {
        initComponents();
        bMesa = new ArrayList<>(); //adiciono todos os 20 botões iniciais no ArrayList
        bMesa.add(btMesa);
        bMesa.add(btMesa1);
        bMesa.add(btMesa2);
        bMesa.add(btMesa3);
        bMesa.add(btMesa4);
        bMesa.add(btMesa5);
        bMesa.add(btMesa6);
        bMesa.add(btMesa7);
        bMesa.add(btMesa8);
        bMesa.add(btMesa9);
        bMesa.add(btMesa10);
        bMesa.add(btMesa11);
        bMesa.add(btMesa12);
        bMesa.add(btMesa13);
        bMesa.add(btMesa14);
        bMesa.add(btMesa15);
        bMesa.add(btMesa16);
        bMesa.add(btMesa17);
        bMesa.add(btMesa18);
        bMesa.add(btMesa19);
        this.setLocationRelativeTo(null);
        bAddConsumo.setEnabled(false); //seto o botão de adicionar consumo como inativo
        bFecharMesa.setEnabled(false); //seto o botão de afechar mesa como inativo
        lTotal.setEnabled(false); //seto o local que descreve o total como inativo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgAcoes = new javax.swing.ButtonGroup();
        pPrincipal = new javax.swing.JPanel();
        bCadastroItens = new javax.swing.JButton();
        bFaturamento = new javax.swing.JButton();
        bFechar = new javax.swing.JButton();
        pConsumo = new javax.swing.JPanel();
        bFecharMesa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaConsumo = new javax.swing.JTable();
        bAbrirMesa = new javax.swing.JButton();
        bAddConsumo = new javax.swing.JButton();
        lTotal = new javax.swing.JLabel();
        tValorTotal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pMesa = new javax.swing.JPanel();
        btMesa = new javax.swing.JButton();
        btMesa1 = new javax.swing.JButton();
        btMesa2 = new javax.swing.JButton();
        btMesa3 = new javax.swing.JButton();
        btMesa4 = new javax.swing.JButton();
        btMesa5 = new javax.swing.JButton();
        btMesa6 = new javax.swing.JButton();
        btMesa7 = new javax.swing.JButton();
        btMesa8 = new javax.swing.JButton();
        btMesa9 = new javax.swing.JButton();
        btMesa10 = new javax.swing.JButton();
        btMesa11 = new javax.swing.JButton();
        btMesa12 = new javax.swing.JButton();
        btMesa13 = new javax.swing.JButton();
        btMesa14 = new javax.swing.JButton();
        btMesa15 = new javax.swing.JButton();
        btMesa16 = new javax.swing.JButton();
        btMesa17 = new javax.swing.JButton();
        btMesa18 = new javax.swing.JButton();
        btMesa19 = new javax.swing.JButton();
        bAddMesa = new javax.swing.JButton();
        bMenosMesa = new javax.swing.JButton();
        tQtdMesa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RESTAURANTE");
        setResizable(false);

        pPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bCadastroItens.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCadastroItens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cadastro.png"))); // NOI18N
        bCadastroItens.setText("CADASTRAR ITENS");
        bgAcoes.add(bCadastroItens);
        bCadastroItens.setPreferredSize(new java.awt.Dimension(200, 60));
        bCadastroItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroItensActionPerformed(evt);
            }
        });

        bFaturamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bFaturamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/faturamento.png"))); // NOI18N
        bFaturamento.setText("FATURAMENTO");
        bFaturamento.setToolTipText("");
        bgAcoes.add(bFaturamento);
        bFaturamento.setPreferredSize(new java.awt.Dimension(215, 60));
        bFaturamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFaturamentoActionPerformed(evt);
            }
        });

        bFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fecharJanela.png"))); // NOI18N
        bFechar.setText("FECHAR");
        bgAcoes.add(bFechar);
        bFechar.setPreferredSize(new java.awt.Dimension(215, 60));
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bCadastroItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bFaturamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bCadastroItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pConsumo.setBorder(javax.swing.BorderFactory.createTitledBorder("CONSUMO"));

        bFecharMesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bFecharMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fecharMesa.png"))); // NOI18N
        bFecharMesa.setText("FECHAR MESA");
        bFecharMesa.setToolTipText("");
        bFecharMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharMesaActionPerformed(evt);
            }
        });

        tabelaConsumo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        tabelaConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qtd.", "ValorUnit.", "ValorTot."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaConsumo);

        bAbrirMesa.setText("Abrir Mesa");
        bAbrirMesa.setFocusable(false);
        bAbrirMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirMesaActionPerformed(evt);
            }
        });

        bAddConsumo.setText("Adicionar Consumo");
        bAddConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddConsumoActionPerformed(evt);
            }
        });

        lTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lTotal.setText("TOTAL:");

        tValorTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tValorTotal.setText("R$ 0,00");

        javax.swing.GroupLayout pConsumoLayout = new javax.swing.GroupLayout(pConsumo);
        pConsumo.setLayout(pConsumoLayout);
        pConsumoLayout.setHorizontalGroup(
            pConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pConsumoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(bFecharMesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pConsumoLayout.createSequentialGroup()
                .addGroup(pConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pConsumoLayout.createSequentialGroup()
                        .addComponent(lTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tValorTotal))
                    .addGroup(pConsumoLayout.createSequentialGroup()
                        .addComponent(bAbrirMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAddConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pConsumoLayout.setVerticalGroup(
            pConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pConsumoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAbrirMesa)
                    .addComponent(bAddConsumo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTotal)
                    .addComponent(tValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bFecharMesa))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MESA"));

        btMesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa.setText("Mesa 1");
        btMesa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa1.setText("Mesa 2");
        btMesa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa2.setText("Mesa 3");
        btMesa2.setToolTipText("");
        btMesa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa3.setText("Mesa 4");
        btMesa3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa4.setText("Mesa 5");
        btMesa4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa5.setText("Mesa 6");
        btMesa5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa6.setText("Mesa 7");
        btMesa6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa7.setText("Mesa 8");
        btMesa7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa8.setText("Mesa 9");
        btMesa8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa9.setText("Mesa 10");
        btMesa9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa10.setText("Mesa 11");
        btMesa10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa10.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa11.setText("Mesa 12");
        btMesa11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa11.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa12.setText("Mesa 13");
        btMesa12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa13.setText("Mesa 14");
        btMesa13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa13.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa14.setText("Mesa 15");
        btMesa14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa14.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa15.setText("Mesa 16");
        btMesa15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa16.setText("Mesa 17");
        btMesa16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa16.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa17.setText("Mesa 18");
        btMesa17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa17.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa18.setText("Mesa 19");
        btMesa18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btMesa19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/talheres.png"))); // NOI18N
        btMesa19.setText("Mesa 20");
        btMesa19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btMesa19.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout pMesaLayout = new javax.swing.GroupLayout(pMesa);
        pMesa.setLayout(pMesaLayout);
        pMesaLayout.setHorizontalGroup(
            pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMesaLayout.createSequentialGroup()
                        .addComponent(btMesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa4))
                    .addGroup(pMesaLayout.createSequentialGroup()
                        .addComponent(btMesa5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa9))
                    .addGroup(pMesaLayout.createSequentialGroup()
                        .addComponent(btMesa10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa14))
                    .addGroup(pMesaLayout.createSequentialGroup()
                        .addComponent(btMesa15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMesa19)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pMesaLayout.setVerticalGroup(
            pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMesa4)
                    .addComponent(btMesa3)
                    .addComponent(btMesa2)
                    .addComponent(btMesa1)
                    .addComponent(btMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMesa5)
                    .addComponent(btMesa6)
                    .addComponent(btMesa7)
                    .addComponent(btMesa8)
                    .addComponent(btMesa9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMesa10)
                    .addComponent(btMesa11)
                    .addComponent(btMesa12)
                    .addComponent(btMesa13)
                    .addComponent(btMesa14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMesa15)
                    .addComponent(btMesa16)
                    .addComponent(btMesa17)
                    .addComponent(btMesa18)
                    .addComponent(btMesa19))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pMesa.setLayout(new GridLayout(0,4));

        jScrollPane2.setViewportView(pMesa);

        bAddMesa.setText("+");
        bAddMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddMesaActionPerformed(evt);
            }
        });

        bMenosMesa.setText("-");
        bMenosMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMenosMesaActionPerformed(evt);
            }
        });

        tQtdMesa.setEditable(false);
        tQtdMesa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tQtdMesa.setText("20");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(bMenosMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tQtdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAddMesa)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddMesa)
                    .addComponent(bMenosMesa)
                    .addComponent(tQtdMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pConsumo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCadastroItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroItensActionPerformed
        new CadastroItens(); //inicializo a janela de Cadastrar Itens
    }//GEN-LAST:event_bCadastroItensActionPerformed

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed
        this.dispose(); //quando clicar na opção cancelar, fecho a página
    }//GEN-LAST:event_bFecharActionPerformed

    private void bFaturamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFaturamentoActionPerformed
        File pdf = new File("Faturamento_Dia.pdf"); //mostro qual é o arquivo que deve ser aberto
        try {
            Desktop.getDesktop().open(pdf); //abro o pdf do faturamento
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro no Desktop: " + ex);
        }
    }//GEN-LAST:event_bFaturamentoActionPerformed

    private void bAddConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddConsumoActionPerformed
        new AddConsumo(tabelaConsumo, tValorTotal); //inicializo a janela de Cadastrar Itens e passo a tabela de Consumo e o Valor Total como parametro para serem modificados
    }//GEN-LAST:event_bAddConsumoActionPerformed

    private void bAbrirMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirMesaActionPerformed
        for (int i = 0; i < bMesa.size(); i++) { //após apertar o botão de abrir mesa, eu mudo a cor deles para verde e deixo ativo os botões de AddConsumo e Fechar mesa
            if (bMesa.get(i).isEnabled()) {
                bMesa.get(i).setBackground(Color.GREEN);
                bAbrirMesa.setEnabled(false); //Deixo intativo o botão de abrir mesa, pois já abri elas
                bAddConsumo.setEnabled(true);
                bFecharMesa.setEnabled(true);
                lTotal.setEnabled(true);
            }
        }
    }//GEN-LAST:event_bAbrirMesaActionPerformed

    private void bAddMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddMesaActionPerformed
        JButton btMesa = new JButton("Mesa " + (bMesa.size() + 1)); //crio um novo botão
        btMesa.setMinimumSize(new Dimension(20, 20)); //seto o tamanho dele
        btMesa.setIcon(new ImageIcon(getClass().getResource("../icons/talheres.png"))); //seto o iconele dele
        btMesa.setVerticalTextPosition(JButton.TOP); //seto o posicionamento do texto
        btMesa.setHorizontalTextPosition(JButton.CENTER);
        bMesa.add(btMesa); //adiciono o novo botão ao ArrayList de botões
        pMesa.add(btMesa); //adiciono o botão ao paionel da Mesa
        revalidate();
        tQtdMesa.setText("" + bMesa.size()); //aumento a quantidade dos botões exitentes
    }//GEN-LAST:event_bAddMesaActionPerformed

    private void bMenosMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMenosMesaActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Deseja Fechar esta Mesa?", "Mesa", JOptionPane.YES_NO_OPTION); //pergunto se o usuário quer fechar a mesa
        if (JOptionPane.YES_OPTION == op) { //se sim, eu removo o botão do painel e removo o botão do ArrayLista
            pMesa.remove(bMesa.get(bMesa.size() - 1));
            bMesa.remove(bMesa.get(bMesa.size() - 1));
            repaint();
            tQtdMesa.setText("" + bMesa.size()); //diminuo a quantidade dos botões exitentes
        }
    }//GEN-LAST:event_bMenosMesaActionPerformed

    private void bFecharMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharMesaActionPerformed
        new FecharMesa(tValorTotal, bAbrirMesa); //inicializo a janela de Fechar Mesa e passo o Valor Total e o botão de Abrir Mesa como parametro para serem modificados
    }//GEN-LAST:event_bFecharMesaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrirMesa;
    private javax.swing.JButton bAddConsumo;
    private javax.swing.JButton bAddMesa;
    private javax.swing.JButton bCadastroItens;
    private javax.swing.JButton bFaturamento;
    private javax.swing.JButton bFechar;
    private javax.swing.JButton bFecharMesa;
    private javax.swing.JButton bMenosMesa;
    private javax.swing.ButtonGroup bgAcoes;
    private javax.swing.JButton btMesa;
    private javax.swing.JButton btMesa1;
    private javax.swing.JButton btMesa10;
    private javax.swing.JButton btMesa11;
    private javax.swing.JButton btMesa12;
    private javax.swing.JButton btMesa13;
    private javax.swing.JButton btMesa14;
    private javax.swing.JButton btMesa15;
    private javax.swing.JButton btMesa16;
    private javax.swing.JButton btMesa17;
    private javax.swing.JButton btMesa18;
    private javax.swing.JButton btMesa19;
    private javax.swing.JButton btMesa2;
    private javax.swing.JButton btMesa3;
    private javax.swing.JButton btMesa4;
    private javax.swing.JButton btMesa5;
    private javax.swing.JButton btMesa6;
    private javax.swing.JButton btMesa7;
    private javax.swing.JButton btMesa8;
    private javax.swing.JButton btMesa9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lTotal;
    private javax.swing.JPanel pConsumo;
    private javax.swing.JPanel pMesa;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JTextField tQtdMesa;
    private javax.swing.JLabel tValorTotal;
    private javax.swing.JTable tabelaConsumo;
    // End of variables declaration//GEN-END:variables
}